#!/usr/bin/env bash
# Makes ~/.tmux.conf load tmux.conf from this repository.
# The repository path is resolved from this script's location, so the
# repository can be cloned anywhere. Rerun the script after moving it.
set -euo pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd -P)"
repo_config="$script_dir/tmux.conf"
target="$HOME/.tmux.conf"

if [[ ! -f "$repo_config" ]]; then
  echo "error: $repo_config not found" >&2
  exit 1
fi

if [[ "$repo_config" == *"'"* ]]; then
  echo "error: tmux cannot source a path with a single quote: $repo_config" >&2
  exit 1
fi

expected="# Generated by $script_dir/install.sh. Edit $repo_config instead.
source-file '$repo_config'"

if [[ -f "$target" && ! -L "$target" && "$(cat "$target")" == "$expected" ]]; then
  echo "$target already loads $repo_config"
  exit 0
fi

if [[ -e "$target" || -L "$target" ]]; then
  stamp="$(date +%Y%m%d%H%M%S)"
  backup="$target.backup.$stamp"
  n=1
  while [[ -e "$backup" || -L "$backup" ]]; do
    backup="$target.backup.$stamp-$n"
    n=$((n + 1))
  done
  mv "$target" "$backup"
  echo "moved existing $target to $backup"
fi

printf '%s\n' "$expected" > "$target"
echo "$target now loads $repo_config"
echo "reload a running tmux with: tmux source-file ~/.tmux.conf"
