#!/usr/bin/env bash
# Makes ~/.tmux.conf load tmux.conf from this repository, then installs the
# plugin manager TPM and the plugins tmux.conf lists, skipping those present.
# The repository path is resolved from this script's location, so the
# repository can be cloned anywhere. Rerun the script after moving it.
set -euo pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd -P)"
repo_config="$script_dir/tmux.conf"
target="$HOME/.tmux.conf"
# tmux.conf runs TPM from this path.
tpm_dir="$HOME/.tmux/plugins/tpm"

link_config() {
  if [[ ! -f "$repo_config" ]]; then
    echo "error: $repo_config not found" >&2
    exit 1
  fi

  if [[ "$repo_config" == *"'"* ]]; then
    echo "error: tmux cannot source a path with a single quote: $repo_config" >&2
    exit 1
  fi

  local expected="# Generated by $script_dir/install.sh. Edit $repo_config instead.
source-file '$repo_config'"

  if [[ -f "$target" && ! -L "$target" && "$(cat "$target")" == "$expected" ]]; then
    echo "$target already loads $repo_config"
    return
  fi

  if [[ -e "$target" || -L "$target" ]]; then
    local stamp backup n=1
    stamp="$(date +%Y%m%d%H%M%S)"
    backup="$target.backup.$stamp"
    while [[ -e "$backup" || -L "$backup" ]]; do
      backup="$target.backup.$stamp-$n"
      n=$((n + 1))
    done
    mv "$target" "$backup"
    echo "moved existing $target to $backup"
  fi

  printf '%s\n' "$expected" > "$target"
  echo "$target now loads $repo_config"
}

# Loads the new config into a tmux server that is already running; without a
# server there is nothing to reload.
reload_running_tmux() {
  if ! tmux list-sessions > /dev/null 2>&1; then
    return
  fi
  tmux source-file "$target"
  echo "reloaded the running tmux"
}

# TPM's command-line installer reads the plugin list from ~/.tmux.conf and the
# files it sources. It finds the plugin folder through the tmux server, which
# learns it when the config runs TPM: a fresh server does so on start, while a
# server running an older config must reload first. A second reload then loads
# the plugins just installed.
install_plugins() {
  if [[ -d "$tpm_dir" ]]; then
    echo "TPM already installed in $tpm_dir"
  else
    git clone --depth 1 https://github.com/tmux-plugins/tpm "$tpm_dir"
  fi
  reload_running_tmux
  "$tpm_dir/bin/install_plugins"
  reload_running_tmux
}

link_config
install_plugins
